### ISSUE TITLE
Add package to PyPi

### ISSUE THREAD

**Issue by dstansby** [USNavalResearchLaboratory/eispac#11]
It would be nice if `eispac` could be packaged and uploaded to the [Python package index](https://pypi.org/) - this would allow users to just do `pip install eispac` to install, instead of having to go through cloning the repository.

**Comment by brianthomas** [comment]
I want to second this, and raise the priority. You are limiting wider use by the community by not being on PyPI.

**Comment by MJWeberg** [comment]
As of July 13th, EISPAC is finally on PyPI! A Conda-forge package may eventually get added, but for now it is not a high priority. Thanks for the feedback and encouragement!
