### ISSUE TITLE
Convert `'__main__'` scripts into examples

### ISSUE THREAD

**Issue by wtbarnes** [USNavalResearchLaboratory/eispac#22]
There are quite a few files throughout the codebase that include `if __name__ == '__main__'` blocks, presumably to show how to use the above code. These should be moved to an example gallery in the docs to make them more visible. As it stands, these are only accessible by reading the source code directly.

**Comment by PaulJWright** [comment]
@wtbarnes @MJWeberg

As mentioned in #3, I would like existing examples to be within the documentation (e.g. https://docs.sunpy.org/en/stable/generated/gallery/index.html). Once issue #3 is fixed, adding these additional examples would significantly improve the usability of this package.

https://github.com/openjournals/joss-reviews/issues/4914
