### ISSUE TITLE
Duplicate functionality in `read_wininfo` and `eis_read_wininfo` 

### ISSUE THREAD

**Issue by wtbarnes** [USNavalResearchLaboratory/eispac#23]
`read_wininfo` and `eis_read_wininfo` in `eispac.templates` appear to be identical or at the very least, provide near equivalent functionality. There is documentation to indicate what either of them does Is there a reason both exist? Can we remove one in favor of the other?

**Comment by wtbarnes** [comment]
There is also `eispac.core.read_wininfo` which seems to be the version that is used in the tutorials

**Comment by MJWeberg** [comment]
Yes, `eis_read_wininfo` is currently being used by some of the command line scripts, but we should be able to just replace it with `eispac.read_wininfo`. I will be cleaning up the scripts soon, right after I finish updating the `download` submodule.

`eispac.core.read_wininfo` is the same script that `eispac.read_wininfo` points to. The code is setup similar to numpy where all of the core functionality is loaded into the top-level `eispac` namespace so as to avoid overly long or redundant function calls. Functions with more limited or specific use cases will be parceled out into submodules as necessary.

**Comment by wtbarnes** [comment]
Resolved in 658e4a8764f5d99dcc27ab11165d83126efd0d10
