### ISSUE TITLE
Hosted documentation

### ISSUE THREAD

**Issue by wtbarnes** [USNavalResearchLaboratory/eispac#3]
[Read the Docs](https://readthedocs.org/) provides an easy way to host documentation online written in either Markdown or restructured text via the Sphinx documentation engine: https://www.sphinx-doc.org/en/master/index.html

I think it would be preferable to refactor the user guide as a section of the documentation and to turn the examples in the user guide and the `scripts/` folder into runnable examples in the documentation via the `sphinx-gallery` tool: https://sphinx-gallery.github.io/stable/index.html. This tool will also autogenerate notebooks that users can download.

The main advantages of this approach is that it ensures that documentation is always up to date as it is rendered on the fly at each check in, it alleviates the need to store large binary files (i.e. PDFs) in the repository, and it provides a higher-level set of integration tests for the code as the examples are re-run each time the documentation is generated. All of these things ensure that the docs do not go "stale" and cut out the number of manual steps required to maintain the docs/software.

**Comment by PaulJWright** [comment]
Hi @MJWeberg @wtbarnes. I would like to see the examples inside the user guide.

Closing this issue would satisfy "Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems)." of my JOSS review: https://github.com/openjournals/joss-reviews/issues/4914

**Comment by MJWeberg** [comment]
All of the examples in `examples/` folder and the `__main__` scripts are actually already contained in the user's guide in the appropriate sections (although the "eispac_tutorial" notebook uses a different time period to coordinate with another tutorial given at the Hinode 14 / IRIS 11 Joint Science Meeting). I have been meaning to build an examples gallery as suggested above, but have not had the chance / opportunity to write new use-cases. For now, I will just work on extracting the current examples.

The `scripts/` folder contains the command line and GUI scripts mentioned in the documentation. I am not sure there would be much utility in converting most them into examples, but the quick-look summary image produced by `eis_plot_fit` might be a another plotting example to add.

**Comment by PaulJWright** [comment]
Sounds good.
