### ISSUE TITLE
Mention the `browse_templates` command line util in docs

### ISSUE THREAD

**Issue by dstansby** [USNavalResearchLaboratory/eispac#43]
I was reading https://eispac.readthedocs.io/en/latest/guide/04-fitting.html#template-files, and left a bit confused as to where to find the template files. Eventually I realised there was a `eis_browse_templates` command - it would be nice to make the documentation reader aware of this in the fitting section of the docs.

**Comment by MJWeberg** [comment]
Thanks for the feedback and sorry for the slow reply. We added a refence as suggested and expanded the documentation earlier this year. Please let us know if anything else is unclear or could use additional / better explanation.
