### ISSUE TITLE
Add some explanations to the "width" and "slit_width"?

### ISSUE THREAD

**Issue by yjzhu-solar** [USNavalResearchLaboratory/eispac#52]
Hi, since there are multiple expressions of the Gaussian width used in Solar physics (e.g., sigma, 1/e width, and FWHM), would you like to add some explanations about the "width" used in the user's guide? Because it takes me some time to figure out that the fitting returns the sigma width. And I also noticed that the "slit_width" restored in the data_cube.meta is in FWHM (I guess because it is calculated from the SSW eis_slit_width.pro). Though the "slit_width" is not used in EISPAC, it might be better to remind the users to avoid confusion.

**Comment by MJWeberg** [comment]
Hello, that is a good point! I will add the definition when I next update the docs. For what it is worth, we are using the sigma widths, which is the standard for EIS data.

You are correct, the "slit_width" metadata is not currently used by EISPAC. It is included mostly for completeness and user reference. I don't _think_ it is technically the FWHM, but I could be mistaken. I will look into it and update the documentation accordingly.

Thanks for using EISPAC!

**Comment by PaulJWright** [comment]
Please address this as part of the JOSS review: https://github.com/openjournals/joss-reviews/issues/4914
