### ISSUE TITLE
Automated build of docs on push/release of version

### ISSUE THREAD

**Issue by PaulJWright** [USNavalResearchLaboratory/eispac#56]
Looking at the docs:

* the last update was 10 months ago: https://readthedocs.org/projects/eispac/builds/, 
* but the most recent (and only) release on pypi was `0.93.3` 4 months ago.

What is the strategy here? Please look into automated building and deployment: https://docs.readthedocs.io/en/stable/features.html.

This is part of the JOSS review: https://github.com/openjournals/joss-reviews/issues/4914

**Comment by PaulJWright** [comment]
This is related to https://github.com/USNavalResearchLaboratory/eispac/issues/3

**Comment by MJWeberg** [comment]
Hello,

We have, unfortunately, had issues getting the docs to automatically build correctly. I believe @wtbarnes and @hpwarren both tried to figure it out a while back and confirmed that all the setting _appear_ to be correct. We will take another look at it, but I am not sure what else there is to try at this point.

Until the very recent addition of the Fido client, there was no significant changes to the code base (aside from the PyPi wheel finally getting uploaded). I will work on updating the user's guide next and hopefully have an update about the build process.

**Comment by PaulJWright** [comment]
Okay, this will be great to get fixed. 

Just so i'm aware what you've tried. Have you set up the webhook, e.g.: 
https://docs.readthedocs.io/en/latest/integrations.html#github

**Comment by MJWeberg** [comment]
After completely rebuilding the docs, we finally fixed the issue with automatic builds on push.
