### ISSUE TITLE
Update Install Documentation Page

### ISSUE THREAD

**Issue by nabobalis** [USNavalResearchLaboratory/eispac#64]
The current documentation (https://github.com/USNavalResearchLaboratory/eispac/blob/main/docs/guide/00-intro.rst#installation) says its not on PyPi but the readme does.

I think this would check off the Installation instructions part of the documentation for the JOSS review: https://github.com/openjournals/joss-reviews/issues/4914

**Comment by MJWeberg** [comment]
This was an oversight on my part, sorry! The docs unfortunately don't update correctly (as mentioned in #56), but we are looking into it again.

**Comment by nabobalis** [comment]
I saw that issue but looking at the actual RST file in the repository, it hasn't been updated.
So when RTD eventually updates, I don't see that changing, unless I am missing something?
